# Generated by Django 5.0.2 on 2024-03-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='photo',
            field=models.ImageField(null=True, upload_to='fotos/'),
        ),
    ]
