# Generated by Django 5.0.2 on 2024-03-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_estacaotrabalho_registroacesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacesso',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
